---
###############################################################################
# Config
###############################################################################
# Decision: do NOT manage web console users - these are dynamically auth'ed and
#     added via connected clients by running 'createwebuser' from the console
#     on a connected server. This is restricted by command permission levels on
#     server settings. Users will have to recreate web user permissions on role
#     application. Standard use (including auto-grant via serveradmin.xml) are
#     not affected.
#
# Reference:
# * https://developer.valvesoftware.com/wiki/7_Days_to_Die_Dedicated_Server

- name:
    '{{ "Update | filesystem | set " ~ seven_days_to_die___app._server_xml }}'
  ansible.builtin.template:
    src: '{{
        seven_days_to_die__cfg._server_config
        if seven_days_to_die__cfg._server_config | length > 0 else
        "templates/default/serverconfig.xml"
      }}'
    dest: '{{ seven_days_to_die___app._server_xml }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0664'  # Game enforced.

- name:
    '{{ "Update | filesystem | set " ~ seven_days_to_die___app._admin_xml }}'
  ansible.builtin.template:
    src: '{{
        seven_days_to_die__cfg._server_admin
        if seven_days_to_die__cfg._server_admin | length > 0 else
        "templates/default/serverconfig.xml"
      }}'
    dest: '{{ seven_days_to_die___app._admin_xml }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0600'  # Game enforced.  TODO - check 0664.
