---
###############################################################################
# Config
###############################################################################
# Decision: do NOT manage web console users - these are dynamically auth'ed and
#     added via connected clients by running 'createwebuser' from the console
#     on a connected server. This is restricted by command permission levels on
#     server settings. Users will have to recreate web user permissions on role
#     application. Standard use (including auto-grant via serveradmin.xml) are
#     not affected.
#
# Reference:
# * https://developer.valvesoftware.com/wiki/7_Days_to_Die_Dedicated_Server

- name: '{{
      "Update | filesystem | set " ~ seven_days_to_die__cfg._config_file
    }}'
  when: seven_days_to_die__cfg._server_config | length > 0
  ansible.builtin.template:
    src: '{{ seven_days_to_die__cfg._server_config }}'
    dest: '{{ seven_days_to_die__cfg._config_file }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0664'  # Game enforced.

- name: '{{
      "Update | filesystem | set minimal " ~
      seven_days_to_die__cfg._config_file
    }}'
  when: seven_days_to_die__cfg._server_config | length == 0
  ansible.builtin.copy:
    src: 'files/default/serverconfig.xml'
    dest: '{{ seven_days_to_die__cfg._config_file }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0664'  # Game enforced.

- name: '{{
      "Update | filesystem | set " ~ seven_days_to_die__cfg._admin_file
    }}'
  when: seven_days_to_die__cfg._server_admin | length > 0
  ansible.builtin.template:
    src: '{{ seven_days_to_die__cfg._server_admin }}'
    dest: '{{ seven_days_to_die__cfg._admin_file }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0600'  # Game enforced.

- name: '{{
      "Update | filesystem | set minimal " ~ seven_days_to_die__cfg._admin_file
    }}'
  when: seven_days_to_die__cfg._server_admin | length == 0
  ansible.builtin.copy:
    src: 'files/default/serverconfig.xml'
    dest: '{{ seven_days_to_die__cfg._admin_file }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0664'  # Game enforced.
