---
###############################################################################
# Install
###############################################################################
# Reference:
# * https://developer.valvesoftware.com/wiki/7_Days_to_Die_Dedicated_Server

- name: 'Install | steamcmd'
  ansible.builtin.import_role:
    name: 'r_pufky.game.steam'
  vars:
    steam_flg_update: false

- name: 'Install | filesystem | find current installation'
  ansible.builtin.stat:
    path: '{{ seven_days_to_die__cfg._app }}'
  register: seven_days_to_die__installed

- name: 'Install | fact | set install state'
  ansible.builtin.set_fact:
    seven_days_to_die__cfg: "{{ seven_days_to_die__cfg | r_pufky.data.v3(

        _is_installed=seven_days_to_die__installed.stat.exists,
        _save_dir=steam__ctx._share ~ '/7DaysToDie/Saves',
      ) }}"

- name: 'Install | filesystem | create server directories'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0755'
    state: 'directory'
  loop:
    - '{{ seven_days_to_die__cfg._root_dir }}'
    - '{{ seven_days_to_die__cfg._save_dir }}'

- name: '{{ "Install | filesystem | " ~ seven_days_to_die__cfg._backup_dir }}'
  when: seven_days_to_die_flg_backup
  ansible.builtin.file:
    path: '{{ seven_days_to_die__cfg._backup_dir }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0755'
    state: 'directory'

- name: 'Install | systemd | set seven_days_to_die.service'
  ansible.builtin.template:
    src: 'systemd/seven_days_to_die.service.j2'
    dest: '/etc/systemd/system/seven_days_to_die.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
