---
###############################################################################
# Pre Execution Tasks
###############################################################################
# Only use data annotations in role after merging role, defaults, runtime data.
# Service may not exist if first install.

- name: 'Prep | fact | record start time'
  ansible.builtin.set_fact:
    seven_days_to_die__srv: "{{ seven_days_to_die___release | r_pufky.data.v3(

        _start=now(utc=True, fmt='%Y-%m-%dT%H%M%S'),

        _update_opts=seven_days_to_die_srv_update_opts | join(' '),
      ) }}"
    seven_days_to_die__cfg: "{{ {} | r_pufky.data.v3(

        _server_config=seven_days_to_die_cfg_server_config,
        _server_admin=seven_days_to_die_cfg_server_admin,
        _backup_d=seven_days_to_die_cfg_backup_d | regex_replace('\\/$', ''),
        _backup_hot=seven_days_to_die_cfg_backup_hot,
        _backup_schedule=seven_days_to_die_cfg_backup_schedule,
      ) }}"

- name: 'Prep | systemd | stop seven_days_to_die.service'
  ansible.builtin.systemd:
    name: 'seven_days_to_die.service'
    state: 'stopped'
  failed_when: false
