---
###############################################################################
# Validate
###############################################################################
# Ensure services and confirm they are active and running.

- name: 'Start | systemd | seven_days_to_die.service'
  ansible.builtin.systemd:
    name: 'seven_days_to_die.service'
    state: 'started'
    enabled: true
    daemon_reload: true
  delay: 15
  retries: 3
  register: seven_days_to_die__service
  until: seven_days_to_die__service.status.ActiveState == 'active'

# Seven Days To Die must be started before first backup timer triggers.
- name: 'Start | meta | 🗘 flush timers 🗘'
  ansible.builtin.meta: flush_handlers

- name: 'Start | fact | query services'
  ansible.builtin.service_facts:

# First time service start can take very long to report running; just check to
# make sure it has not immediately failed from a bad configuration.
- name: 'Start | assert | services running'
  ansible.builtin.assert:
    quiet: true
    that: ansible_facts.services[item].state != 'failed'
    fail_msg: |

      ✘ Service failed to start.
      {{ item }}
  loop:
    - 'seven_days_to_die.service'

- name: 'Start | systemd | query seven_days_to_die_backup.timer'
  when: seven_days_to_die_flg_backup
  ansible.builtin.command: 'systemctl status seven_days_to_die_backup.timer'
  changed_when: false
  register: seven_days_to_die__cmd

- name: 'Start | assert | seven_days_to_die_backup.timer active'
  when: seven_days_to_die_flg_backup
  ansible.builtin.assert:
    quiet: true
    that:
      - seven_days_to_die__cmd.rc == 0
      - '"Active: active" in seven_days_to_die__cmd.stdout'
    fail_msg: |

      ✘ seven_days_to_die_backup.timer should be active.

- name: 'Start | assert | seven_days_to_die_backup.service enabled'
  when: seven_days_to_die_flg_backup
  ansible.builtin.assert:
    quiet: true
    that: ansible_facts.services[item].status == 'enabled'
    fail_msg: |

      ✘ Service should be enabled.
      {{ item }}
  loop:
    - 'seven_days_to_die_backup.service'
