---
# yamllint disable rule:line-length
###############################################################################
# Default
###############################################################################
# Default values result in running Seven Days to Die server.
#
# Tests:
# * serveradmin.xml is rendered correctly.
# * serverconfig.xml is rendered correctly.
# * Backup service/timeer with hot backups disabled are correct.
# * Admins are created.
# * Whitelist is correct.
# * API tokens are correct.
# * Seven Days to Die server is running.

dependency:
  name: 'galaxy'
driver:
  name: 'vagrant'
  provider:
    name: 'libvirt'
    type: 'libvirt'
provisioner:
  name: 'ansible'
  connection_options:
    ansible_ssh_user: 'vagrant'
    ansible_become: true
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
  inventory:
    group_vars:
      all:
        url_inject_enable: true
        seven_days_to_die_flg_backup: true
        seven_days_to_die_cfg_server_config: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/files/secured/serverconfig.xml"
          }}'
        seven_days_to_die_cfg_server_admin: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/files/secured/serveradmin.xml"
          }}'
platforms:
  - name: 'seven-days-to-die-default'
    box: 'debian/trixie64'
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: 'private_network'
        auto_config: true
        type: 'dhcp'
    instance_raw_config_args:
      - 'vm.network "forwarded_port", guest: 26900, host: 26900, protocol: "udp"'
      - 'vm.network "forwarded_port", guest: 26901, host: 26901, protocol: "udp"'
      - 'vm.network "forwarded_port", guest: 26902, host: 26902, protocol: "udp"'
      - 'vm.network "forwarded_port", guest: 26903, host: 26903, protocol: "udp"'
      - 'vm.network "forwarded_port", guest: 26900, host: 26900, protocol: "tcp"'
      - 'vm.network "forwarded_port", guest: 8080, host: 8080, protocol: "tcp"'
      - 'vm.network "forwarded_port", guest: 8081, host: 8081, protocol: "tcp"'
verifier:
  name: 'ansible'
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'converge'
    - 'verify'
    - 'destroy'
