---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Prepare | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name:
        '{{ "Verify | xml | query " ~ seven_days_to_die___app._config_file }}'
      community.general.xml:
        path: '{{ seven_days_to_die___app._config_file }}'
        content: 'attribute'
        xpath: '/ServerSettings/property[@name="TelnetEnabled"]'
      register: seven_days_to_die__test

    - name: 'Verify | fact | parse serverconfig.xml'
      ansible.builtin.set_fact:
        seven_days_to_die__test_xml:
          '{{ seven_days_to_die__test.matches[0].property.value }}'

    - name: 'Verify | assert | Preferences.xml TelnetEnabled false'
      ansible.builtin.assert:
        quiet: true
        that:
          - seven_days_to_die__test_xml == 'false'
        fail_msg: |

          ✘ TelnetEnabled should be false.
